### PR TITLE
Fix: fetch regular expression should only select rel='next' (fixes #275)

### LINKED ISSUE #275: API erroring when fetching more than 2 pages of content.
### What happened?

When trying to load the third page of content the apiCollection gets stuck in an infinte loop throwing constant errors (shown below). The regular expression in fetch isn't only pulling the next page but also the previous leading to the issue.

### Expected behaviour

_No response_

### Steps to reproduce

Create a course with more than 200 items. 

### Authoring tool version

rc4

### Framework version

_No response_

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```sh
2024-01-18T14:25:02.496Z warn content failed to parse query page param 'undefined', SyntaxError: Unexpected token > in JSON at position 1
```

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Add a link to the original issue)
#275 

[//]: # (Delete as appropriate)
### Fix
* fetch regular expression only selecting rel='next' (fixes #275)

### CODE REVIEW

**Comment by joe-allen-89** [comment]
@taylortom can you cast an eye over this, ideally I wanted to keep it to one expression but couldn't get it to only pull next without splitting it up.

**Comment by chris-steele** [comment]
@joe-allen-89 just noticed this and wondered if it might resolve https://github.com/adapt-security/adapt-authoring-api/issues/5#issuecomment-1614796483

**Comment by chris-steele** [comment]
@joe-allen-89 will this need to be applied to no-sidebar also?

**Review by chris-steele — APPROVED** [review]

**Comment by taylortom** [comment]
Works for me :fire: 

***

FYI you can reduce the page size for easier testing using: 
```js
{
   // other config omitted
  'adapt-authoring-api': {
    defaultPageSize: X
  }
}
```

**Review by taylortom — APPROVED** [review]

**Pull request merged**
