### PR TITLE
Update: Show all courses in shared as per legacy behaviour (fixes #310)

### LINKED ISSUE #310: Shared courses do not appear in shared dashboard
### What happened?

https://github.com/cgkineo/adapt-authoring/issues/26

### Expected behaviour

_No response_

### Steps to reproduce

https://github.com/cgkineo/adapt-authoring/issues/26

### Authoring tool version

https://github.com/cgkineo/adapt-authoring/issues/26

### Framework version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chris-steele**
#310 

### Update
* Show all courses in shared as per legacy behaviour

### CODE REVIEW

**Review by taylortom — COMMENTED** [review]
Does this not also remove the functionality of showing your own courses?

**Comment by chris-steele** [comment]
@taylortom apologies, I interpreted the ticket (and the proposal that the two views would be combined in v1.1) as we should show the same content in both views - have amended it as per your comment 👍

**Comment by taylortom** [comment]
Apologies, I've had a look/test of the code, and I've not actually found a way (server-side) to filter the courses as we did in legacy.

I propose maybe merging the two pages now

**Comment by kineopete** [comment]
I vote for leaving the behaviour as is for now - it's a minor behaviour change for users to adopt and not a major encumbrance.

**Pull request closed without merging**
